{% set name = "xradarsat2" %}
{% set version = "2023.5.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xradarsat2-{{ version }}.tar.gz
  sha256: a466617b5b6173e41cc54c725268db5804b122c954059dfe0d2d89cd0dc2ac88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61.0
    - setuptools_scm >=6.2
  run:
    - python >=3.9
    - xmltodict
    - numpy
    - xarray
    - xarray-datatree
    - rasterio
    - rioxarray
    - dask-core
    - affine
    - regex
    - pyyaml

test:
  imports:
    - xradarsat2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/xradarsat2/
  summary: xarray/dask distributed L1 sar file reader for radarSat2
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/umr-lops/xradarsat2/
  doc_url: https://cerweb.ifremer.fr/datarmor/doc_lib_reader_RS2/html/
extra:
  recipe-maintainers:
    - yreynaud
    - agrouaze
